import fs from 'node:fs';
import path from 'node:path';

// Original practice material aligned to the topics and grammar goals in the supplied slides.
// The textbook's dialogues, exercises, and artwork are not copied.
const lessons = [
  {id:'u02',title:'취미 활동',subtitle:'좋아하는 일과 자주 하는 일을 말해 봐요.',words:[['취미','hobby'],['자전거','bicycle'],['수영','swimming'],['자주','often'],['피아노','piano']],grammar:[['못','동사 앞에 놓아 할 수 없거나 하지 못하는 일을 말해요.','저는 수영을 못 해요.','I cannot swim.'],['-아서/어서','앞의 일이 뒤의 일의 이유가 될 때 사용해요.','날씨가 좋아서 자전거를 타요.','I ride a bike because the weather is nice.']],lines:[['나영','시간이 있을 때 무엇을 해요?','What do you do when you have time?'],['준호','저는 피아노를 쳐요. 그런데 수영은 못 해요.','I play piano. But I cannot swim.'],['나영','저는 자전거를 자주 타요. 좋아해서 매주 타요.','I ride a bike often. I ride every week because I like it.']]},
  {id:'u03',title:'음식',subtitle:'음식의 맛을 이야기하고 주문해 봐요.',words:[['음식','food'],['맛','taste'],['비빔밥','bibimbap'],['국수','noodles'],['맵다','to be spicy']],grammar:[['-(으)ㄹ래요','먹거나 마시고 싶은 것을 묻거나 말할 때 사용해요.','저는 따뜻한 국수를 먹을래요.','I would like to eat warm noodles.'],['무슨','종류를 물을 때 명사 앞에 사용해요.','무슨 음식을 좋아해요?','What kind of food do you like?']],lines:[['지수','점심에 무슨 음식을 먹을래요?','What food would you like for lunch?'],['에밀','저는 비빔밥을 먹을래요. 많이 매워요?','I would like bibimbap. Is it very spicy?'],['지수','조금 매워요. 덜 맵게 해 달라고 할 수 있어요.','It is a little spicy. You can ask for it to be less spicy.']]},
  {id:'u04',title:'교통',subtitle:'교통수단과 걸리는 시간을 이야기해요.',words:[['버스','bus'],['지하철','subway'],['택시','taxi'],['시간','time'],['걸리다','to take (time)']],grammar:[['이/가 걸리다','어떤 일을 하는 데 필요한 시간을 말할 때 사용해요.','역까지 십 분이 걸려요.','It takes ten minutes to the station.'],['-에서 -까지','출발하는 곳과 도착하는 곳을 함께 말할 때 사용해요.','집에서 학교까지 지하철을 타요.','I take the subway from home to school.']],lines:[['리나','도서관까지 어떻게 가요?','How do you get to the library?'],['도윤','버스를 타요. 여기에서 십오 분쯤 걸려요.','I take a bus. It takes about fifteen minutes from here.'],['리나','그럼 버스 정류장으로 갈게요.','Then I will go to the bus stop.']]},
  {id:'u05',title:'길 찾기',subtitle:'위치를 묻고 길을 안내해 봐요.',words:[['오른쪽','right side'],['왼쪽','left side'],['똑바로','straight ahead'],['건너다','to cross'],['건물','building']],grammar:[['(으)로','이동하는 방향을 나타낼 때 사용해요.','이 길로 계속 가세요.','Please keep going along this road.'],['-아/어서','순서대로 이어지는 동작을 말할 때 사용해요.','길을 건너서 왼쪽으로 가세요.','Cross the road and go left.']],lines:[['유진','미술관이 어디에 있어요?','Where is the art museum?'],['현우','앞으로 쭉 가서 오른쪽으로 도세요.','Go straight ahead and turn right.'],['유진','오른쪽 건물인가요? 고마워요.','Is it the building on the right? Thank you.']]},
  {id:'u06',title:'전화',subtitle:'전화와 메시지로 필요한 말을 전해요.',words:[['전화','phone call'],['전화번호','phone number'],['문자 메시지','text message'],['전화를 받다','to answer a call'],['연락하다','to contact']],grammar:[['-아/어 주다','다른 사람을 위해 하는 행동이나 부탁을 말해요.','나중에 전화해 주세요.','Please call me later.'],['-지요?','상대에게 확인하거나 동의를 구할 때 사용해요.','내일 만날 수 있지요?','We can meet tomorrow, right?']],lines:[['서연','지금 통화할 수 있어요?','Can you talk now?'],['마테오','지금은 회의 중이에요. 문자 메시지를 보내 주세요.','I am in a meeting now. Please send a text.'],['서연','네, 끝나면 연락해 주세요.','Okay, please contact me when it ends.']]},
  {id:'u07',title:'외모',subtitle:'사람의 모습과 옷차림을 설명해요.',words:[['외모','appearance'],['옷차림','outfit'],['안경','glasses'],['모자','hat'],['키가 크다','to be tall']],grammar:[['-(으)ㄴ','형용사가 뒤의 명사를 꾸밀 때 사용해요.','키가 큰 사람이 제 친구예요.','The tall person is my friend.'],['-고 있다','지금 하고 있는 행동이나 입고 있는 상태를 나타내요.','빨간 모자를 쓰고 있어요.','They are wearing a red hat.']],lines:[['다혜','입구에 있는 제 친구가 보여요?','Can you see my friend at the entrance?'],['민호','어떤 분이에요?','What do they look like?'],['다혜','키가 크고 파란 셔츠를 입고 있어요.','They are tall and wearing a blue shirt.']]},
  {id:'u08',title:'가족',subtitle:'가족을 소개하고 높임말을 익혀요.',words:[['가족','family'],['할아버지','grandfather'],['할머니','grandmother'],['부모님','parents'],['동생','younger sibling']],grammar:[['의','소유나 관계를 나타낼 때 두 명사 사이에 사용해요.','이분은 저의 할머니예요.','This is my grandmother.'],['-(으)시-','어른이나 존중하는 사람의 행동을 높여 말해요.','아버지는 요리를 잘하세요.','My father cooks well.']],lines:[['소라','가족이 몇 명이에요?','How many people are in your family?'],['지안','네 명이에요. 부모님하고 동생이 있어요.','Four. I have my parents and a younger sibling.'],['소라','동생도 한국어를 배워요?','Does your sibling also learn Korean?']]},
  {id:'u09',title:'여행',subtitle:'다녀온 곳과 가고 싶은 곳을 이야기해요.',words:[['여행','travel'],['여행지','travel destination'],['바다','sea'],['산','mountain'],['계획','plan']],grammar:[['-아/어 보다','어떤 일을 경험해 봤다는 뜻으로 사용해요.','제주도에 가 봤어요.','I have been to Jeju Island.'],['-고 싶다','하고 싶은 일을 말할 때 사용해요.','다음에는 바다를 보고 싶어요.','Next time I want to see the sea.']],lines:[['다니엘','이번 방학에 어디에 가고 싶어요?','Where do you want to go this vacation?'],['민아','강릉에 가서 바다를 보고 싶어요.','I want to go to Gangneung and see the sea.'],['다니엘','저도 가 봤어요. 조용한 곳도 많아요.','I have been there too. There are many quiet places.']]},
  {id:'u10',title:'건강',subtitle:'몸 상태를 말하고 조언해요.',words:[['건강','health'],['머리','head'],['배','stomach'],['아프다','to hurt / be sick'],['약','medicine']],grammar:[['-지 말다','어떤 행동을 하지 말라고 조언할 때 사용해요.','오늘은 늦게 자지 마세요.','Please do not go to bed late today.'],['-(으)ㄴ 후에','한 일이 끝난 다음에 하는 일을 말해요.','밥을 먹은 후에 약을 드세요.','Take the medicine after eating.']],lines:[['아린','얼굴이 안 좋아 보여요. 어디 아파요?','You do not look well. Are you sick?'],['현수','네, 머리가 조금 아파요.','Yes, I have a slight headache.'],['아린','물을 마시고 푹 쉬세요.','Drink some water and get plenty of rest.']]},
  {id:'u11',title:'모임',subtitle:'모임을 준비하고 약속을 정해요.',words:[['모임','gathering'],['초대하다','to invite'],['준비하다','to prepare'],['예약하다','to reserve'],['선물','gift']],grammar:[['-아야/어야 하다','반드시 해야 하는 일을 말해요.','모임 전에 장소를 예약해야 해요.','We must reserve a place before the gathering.'],['-(으)ㄹ게요','상대에게 자신의 의지나 약속을 말해요.','제가 음료를 준비할게요.','I will prepare the drinks.']],lines:[['윤아','토요일 모임은 어디에서 할까요?','Where shall we hold Saturday’s gathering?'],['정민','작은 카페를 예약할게요.','I will reserve a small café.'],['윤아','좋아요. 저는 친구들에게 연락할게요.','Great. I will contact our friends.']]},
  {id:'u12',title:'고향',subtitle:'고향의 모습과 특징을 비교해요.',words:[['고향','hometown'],['도시','city'],['시골','countryside'],['조용하다','to be quiet'],['공기','air']],grammar:[['-지만','서로 다른 두 상황을 대조할 때 사용해요.','제 고향은 작지만 활기차요.','My hometown is small but lively.'],['보다','두 대상을 비교할 때 기준 뒤에 붙여요.','고향이 이 도시보다 조용해요.','My hometown is quieter than this city.']],lines:[['루카','고향은 어떤 곳이에요?','What is your hometown like?'],['혜진','바다 옆에 있는 작은 도시예요.','It is a small city by the sea.'],['루카','여기보다 조용해요?','Is it quieter than here?'],['혜진','네, 조용하지만 볼거리가 많아요.','Yes, it is quiet, but there is a lot to see.']]},
  {id:'u13',title:'기분과 감정',subtitle:'기분을 말하고 기분을 바꾸는 방법을 나눠요.',words:[['기분','mood'],['감정','emotion'],['기쁘다','to be happy'],['외롭다','to be lonely'],['스트레스','stress']],grammar:[['-(으)ㄹ 때','어떤 일이 일어나는 시간이나 상황을 말해요.','기분이 안 좋을 때 산책해요.','I take a walk when I feel down.'],['-(으)러 가다','어떤 장소에 가는 목적을 말해요.','친구를 만나러 카페에 가요.','I go to a café to meet a friend.']],lines:[['보라','요즘 스트레스가 많아요.','I have a lot of stress these days.'],['태오','기분이 안 좋을 때 무엇을 해요?','What do you do when you feel down?'],['보라','공원에 걸으러 가요. 그러면 기분이 좋아져요.','I go to the park to walk. Then I feel better.']]},
  {id:'u14',title:'미래',subtitle:'꿈과 앞으로의 계획을 이야기해요.',words:[['미래','future'],['꿈','dream'],['계획','plan'],['졸업하다','to graduate'],['성공하다','to succeed']],grammar:[['-(으)려고','어떤 행동의 목적이나 의도를 말해요.','한국어를 더 배우려고 매일 공부해요.','I study every day to learn more Korean.'],['-(으)면','어떤 조건이 이루어진 뒤의 일을 말해요.','시간이 있으면 한국 영화를 볼 거예요.','If I have time, I will watch a Korean movie.']],lines:[['나래','졸업하면 무엇을 하고 싶어요?','What do you want to do after graduation?'],['레오','저는 사람들을 가르치려고 해요.','I intend to teach people.'],['나래','멋진 꿈이에요! 저는 글을 쓰고 싶어요.','That is a wonderful dream! I want to write.']]}
];

const cultures = [
  {id:'c01',title:'한국 음식',reading:'한국에서는 밥과 국, 여러 반찬을 함께 먹는 식사가 흔해요. 식당에서 음식을 주문할 때 매운 정도를 물어볼 수도 있어요. 처음 먹는 음식이라면 친구에게 맛과 재료를 물어보세요.',question:'한국 음식을 처음 먹을 때 도움이 되는 행동은?',choices:['맛과 재료를 물어본다.','메뉴를 보지 않는다.','친구에게 아무 말도 하지 않는다.'],answer:0},
  {id:'c02',title:'한국의 대중교통',reading:'한국의 도시에서는 버스와 지하철을 쉽게 볼 수 있어요. 같은 목적지까지 가는 방법이 여러 가지일 수 있으므로 시간과 갈아타는 횟수를 비교하면 좋아요. 길을 잘 모르면 정류장이나 역 이름을 먼저 확인해 보세요.',question:'목적지로 가는 방법을 고를 때 비교하면 좋은 것은?',choices:['시간과 갈아타는 횟수','날씨와 옷 색깔','식당의 메뉴'],answer:0},
  {id:'c03',title:'한국의 여행지',reading:'한국에는 바다가 가까운 도시, 산이 아름다운 지역, 오래된 건물이 남아 있는 곳이 있어요. 여행할 때는 가고 싶은 장소를 정하고 이동 시간을 살펴보세요. 계절에 따라 같은 곳도 다른 풍경을 보여 줍니다.',question:'여행을 계획할 때 살펴볼 것으로 알맞은 것은?',choices:['이동 시간','친구의 전화번호만','모임의 선물만'],answer:0},
  {id:'c04',title:'한국 사람들의 모임',reading:'친구들과 모일 때는 장소와 시간을 먼저 정해요. 함께 먹을 음식이나 준비할 물건을 나누어 맡기도 해요. 약속이 바뀌면 미리 알려 주면 모두가 편하게 모일 수 있어요.',question:'모임 약속이 바뀌면 어떻게 하면 좋을까요?',choices:['미리 알려 준다.','아무에게도 말하지 않는다.','시간을 잊어버린다.'],answer:0}
];

const manifestPath='content/manifest.json';
const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
for(const lesson of lessons) {
  const vocabulary=lesson.words.map(([ko,meaning],i)=>({id:`${lesson.id}-v${String(i+1).padStart(2,'0')}`,ko,romanization:'',meaning,audio:null}));
  const grammar=lesson.grammar.map(([pattern,explanation,ko,meaning],i)=>({id:`${lesson.id}-g${String(i+1).padStart(2,'0')}`,pattern,explanation,examples:[{ko,meaning}]}));
  const dialogue={audio:null,lines:lesson.lines.map(([speaker,text,meaning])=>({speaker,text,meaning}))};
  const quiz=[
    {id:`${lesson.id}-q01`,type:'multiple-choice',question:`‘${vocabulary[0].ko}’의 뜻은 무엇인가요?`,choices:[vocabulary[0].meaning,vocabulary[1].meaning,vocabulary[2].meaning],answer:0,explanation:`‘${vocabulary[0].ko}’는 ‘${vocabulary[0].meaning}’라는 뜻이에요.`,hint:['첫 번째 어휘 카드를 떠올려 보세요.','영어 뜻을 비교해 보세요.',`정답은 ‘${vocabulary[0].meaning}’이에요.`]},
    {id:`${lesson.id}-q02`,type:'multiple-choice',question:`‘${grammar[0].pattern}’를 사용한 문장은?`,choices:[grammar[0].examples[0].ko,grammar[1].examples[0].ko,'오늘은 금요일이에요.'],answer:0,explanation:`‘${grammar[0].examples[0].ko}’에 이 문형이 쓰였어요.`,hint:['첫 번째 문법 카드를 떠올려 보세요.','예문을 비교해 보세요.',`‘${grammar[0].examples[0].ko}’를 골라요.`]}
  ];
  const data={unitId:lesson.id,title:lesson.title,kind:'lesson',subtitle:lesson.subtitle,vocabulary,grammar,dialogue,quiz,minigames:[{type:'matching',pairs:vocabulary.slice(0,3).map(v=>[v.ko,v.meaning])}],rewards:{xpOnComplete:50,badge:`${lesson.title} 첫걸음`}};
  fs.writeFileSync(path.join('content/units',`${lesson.id}.json`),JSON.stringify(data,null,2)+'\n');
  manifest.units.find(x=>x.unitId===lesson.id).content=`/content/units/${lesson.id}.json`;
}
for(const culture of cultures) {
  const data={unitId:culture.id,title:culture.title,kind:'culture',vocabulary:[],grammar:[],dialogue:{audio:null,lines:[]},quiz:[],reading:culture.reading,comprehension:{id:`${culture.id}-q01`,type:'multiple-choice',question:culture.question,choices:culture.choices,answer:culture.answer,explanation:'읽은 내용을 다시 확인해 보세요.',hint:['글을 천천히 다시 읽어 보세요.','첫 번째 선택지를 살펴보세요.','정답은 첫 번째 선택지예요.']},rewards:{xpOnComplete:20,badge:`${culture.title} 탐험가`}};
  fs.writeFileSync(path.join('content/units',`${culture.id}.json`),JSON.stringify(data,null,2)+'\n');
  manifest.units.find(x=>x.unitId===culture.id).content=`/content/units/${culture.id}.json`;
}
fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');
console.log('Created 13 lessons and 4 culture corners.');
