import { extraGrammar } from './grammar-extra.js';
export const languageOptions=[['ko','한국어'],['en','English'],['ja','日本語'],['zh','中文'],['vi','Tiếng Việt'],['ne','नेपाली'],['th','ไทย'],['uz','Oʻzbekcha'],['mn','Монгол']];
const navigation={
  ko:['학습 대시보드','전체 단원','오늘의 복습','첫 수업 시작하기','이전 활동','다음 활동','학습 완료하기','정답 확인','다시 풀기'],
  en:['Dashboard','All lessons','Review today','Start lesson 1','Previous','Next activity','Finish lesson','Check answer','Try again'],
  ja:['学習ホーム','全レッスン','今日の復習','第1課を始める','前へ','次の活動','レッスン完了','答えを確認','もう一度'],
  zh:['学习首页','全部单元','今日复习','开始第1课','上一项','下一项活动','完成课程','确认答案','再试一次'],
  vi:['Trang học','Tất cả bài học','Ôn tập hôm nay','Bắt đầu bài 1','Trước','Hoạt động tiếp','Hoàn thành bài','Kiểm tra đáp án','Thử lại'],
  ne:['सिकाइ पृष्ठ','सबै पाठ','आजको पुनरावृत्ति','पहिलो पाठ सुरु','अघिल्लो','अर्को गतिविधि','पाठ समाप्त','उत्तर जाँच्नुहोस्','फेरि प्रयास'],
  th:['หน้าหลักการเรียน','บทเรียนทั้งหมด','ทบทวนวันนี้','เริ่มบทที่ 1','ก่อนหน้า','กิจกรรมถัดไป','จบบทเรียน','ตรวจคำตอบ','ลองอีกครั้ง'],
  uz:['Bosh sahifa','Barcha darslar','Bugungi takror','1-darsni boshlash','Oldingi','Keyingi mashq','Darsni yakunlash','Javobni tekshirish','Qayta urinish'],
  mn:['Сурах нүүр','Бүх хичээл','Өнөөдрийн давтлага','1-р хичээлийг эхлэх','Өмнөх','Дараагийн дасгал','Хичээлийг дуусгах','Хариуг шалгах','Дахин оролдох']
};
const navigationKeys=['dashboard','units','review','start','previous','next','finish','check','retry'];
const languageLabels={ko:'설명 언어',en:'Guide language',ja:'説明の言語',zh:'说明语言',vi:'Ngôn ngữ hướng dẫn',ne:'निर्देशनको भाषा',th:'ภาษาคำอธิบาย',uz:'Yo‘riqnoma tili',mn:'Тайлбарын хэл'};
export function ui(lang,key){if(key==='language')return languageLabels[lang]||languageLabels.en;const i=navigationKeys.indexOf(key);return i<0?key:(navigation[lang]||navigation.en)[i];}
const messages={
  ko:{answerFirst:'정답을 확인한 뒤 다음으로 가세요.',speechUnavailable:'이 브라우저에서는 음성 재생을 사용할 수 없어요.',scene:'대화를 읽고 어떤 상황인지 생각해 보세요. 한국어 문장을 소리 내어 읽어 보세요.',words:'그림 기호를 보며 한국어 단어를 익히고 발음을 들어 보세요.',grammar:'이 표현이 언제 쓰이는지 예문과 함께 살펴보세요.',listening:'질문을 먼저 읽고 한국어 음성을 들어 보세요. 대본을 열 수도 있어요.',speaking:'배운 표현을 써서 자신의 이야기를 소리 내어 말해 보세요.',reading:'글을 읽고 중심 내용을 찾은 뒤 질문에 답해 보세요.',writing:'짧게라도 직접 써 보세요. 글은 이 브라우저에 저장할 수 있어요.',quiz:'문제를 풀고 정답을 확인한 뒤 다음으로 가세요.',tts:'브라우저의 한국어 합성 음성입니다. 실제 교재 음원은 아닙니다.'},
  en:{answerFirst:'Check the correct answer before continuing.',speechUnavailable:'Speech playback is not available in this browser.',scene:'Read the dialogue and picture the situation. English meanings appear below each line.',words:'Use the picture symbols and English meanings to learn each Korean word.',grammar:'See when this pattern is used, then read the example aloud.',listening:'Read the question first, then listen in Korean. You can open the transcript.',speaking:'Use today’s expressions to talk about yourself aloud.',reading:'Read for the main idea, then answer the question.',writing:'Write a few sentences in Korean. Your draft can be saved in this browser.',quiz:'Answer the questions and check each answer before continuing.',tts:'This uses your browser’s Korean synthetic voice, not the textbook recording.'},
  ja:{answerFirst:'正解を確認してから次へ進んでください。',speechUnavailable:'このブラウザーでは音声を再生できません。',scene:'会話を読み、場面を想像しましょう。各文の下に日本語訳があります。',words:'絵記号と日本語の意味を見ながら韓国語の単語を覚えましょう。',grammar:'この文型を使う場面を確認し、例文を声に出して読みましょう。',listening:'先に質問を読み、韓国語を聞きましょう。スクリプトも表示できます。',speaking:'今日の表現を使って、自分のことを声に出して話しましょう。',reading:'文章の要点をつかみ、質問に答えましょう。',writing:'韓国語で短い文章を書きましょう。下書きはこのブラウザーに保存できます。',quiz:'各問題を解き、正解を確認してから進みましょう。',tts:'ブラウザーの韓国語合成音声を使用します。教科書の音声ではありません。'},
  zh:{answerFirst:'请先确认正确答案，再继续。',speechUnavailable:'此浏览器无法播放语音。',scene:'阅读对话并想象情境。每句下方附有中文释义。',words:'结合图标和中文释义学习韩语词汇。',grammar:'了解句型的使用场景，再大声读例句。',listening:'先看问题，再听韩语。需要时可以打开文字稿。',speaking:'用今天学到的表达，说说自己的情况。',reading:'阅读短文、抓住大意，然后回答问题。',writing:'试着用韩语写几句话。草稿可以保存在此浏览器中。',quiz:'完成题目并确认答案后继续。',tts:'这里使用浏览器的韩语合成语音，不是教材录音。'},
  vi:{answerFirst:'Hãy kiểm tra đáp án đúng trước khi tiếp tục.',speechUnavailable:'Trình duyệt này không hỗ trợ phát giọng nói.',scene:'Đọc hội thoại và hình dung tình huống. Nghĩa tiếng Việt nằm dưới mỗi câu.',words:'Học từ tiếng Hàn qua biểu tượng và nghĩa tiếng Việt.',grammar:'Xem khi nào dùng mẫu câu này rồi đọc to ví dụ.',listening:'Đọc câu hỏi trước, sau đó nghe tiếng Hàn. Bạn có thể mở bản chép lời.',speaking:'Dùng các mẫu câu vừa học để nói về bản thân.',reading:'Đọc ý chính của đoạn văn rồi trả lời câu hỏi.',writing:'Hãy viết vài câu bằng tiếng Hàn. Bản nháp có thể lưu trong trình duyệt này.',quiz:'Làm bài và kiểm tra đáp án trước khi tiếp tục.',tts:'Ứng dụng dùng giọng tổng hợp tiếng Hàn của trình duyệt, không phải âm thanh của sách.'},
  ne:{answerFirst:'अगाडि बढ्नुअघि सही उत्तर जाँच्नुहोस्।',speechUnavailable:'यो ब्राउजरमा आवाज चलाउन सकिँदैन।',scene:'संवाद पढ्नुहोस् र अवस्था कल्पना गर्नुहोस्। प्रत्येक वाक्यको तल नेपाली अर्थ छ।',words:'चित्र सङ्केत र नेपाली अर्थ हेरेर कोरियाली शब्द सिक्नुहोस्।',grammar:'यो व्याकरण कहिले प्रयोग हुन्छ हेर्नुहोस् र उदाहरण ठूलो स्वरमा पढ्नुहोस्।',listening:'पहिले प्रश्न पढ्नुहोस्, त्यसपछि कोरियाली सुन्नुहोस्। लेखिएको पाठ पनि खोल्न सकिन्छ।',speaking:'आज सिकेका अभिव्यक्ति प्रयोग गरेर आफ्नो बारेमा ठूलो स्वरमा बोल्नुहोस्।',reading:'मुख्य विचार बुझेर प्रश्नको उत्तर दिनुहोस्।',writing:'कोरियालीमा केही वाक्य लेख्नुहोस्। मस्यौदा यही ब्राउजरमा राख्न सकिन्छ।',quiz:'प्रश्नको उत्तर दिनुहोस् र अगाडि बढ्नुअघि उत्तर जाँच्नुहोस्।',tts:'यो ब्राउजरको कृत्रिम कोरियाली आवाज हो, पाठ्यपुस्तकको रेकर्डिङ होइन।'},
  th:{answerFirst:'ตรวจคำตอบที่ถูกต้องก่อนดำเนินการต่อ',speechUnavailable:'เบราว์เซอร์นี้ไม่รองรับการเล่นเสียง',scene:'อ่านบทสนทนาและนึกภาพสถานการณ์ ความหมายภาษาไทยอยู่ใต้แต่ละประโยค',words:'เรียนคำศัพท์เกาหลีด้วยสัญลักษณ์ภาพและความหมายภาษาไทย',grammar:'ดูว่ารูปแบบนี้ใช้เมื่อใด แล้วอ่านตัวอย่างออกเสียง',listening:'อ่านคำถามก่อนแล้วฟังภาษาเกาหลี สามารถเปิดบทพูดได้',speaking:'ใช้สำนวนที่เรียนวันนี้พูดเรื่องของตนเองออกเสียง',reading:'อ่านเพื่อจับใจความสำคัญ แล้วตอบคำถาม',writing:'ลองเขียนภาษาเกาหลีสั้น ๆ บันทึกร่างไว้ในเบราว์เซอร์นี้ได้',quiz:'ตอบคำถามและตรวจคำตอบก่อนดำเนินการต่อ',tts:'ใช้เสียงภาษาเกาหลีสังเคราะห์ของเบราว์เซอร์ ไม่ใช่เสียงจากหนังสือเรียน'},
  uz:{answerFirst:'Davom etishdan oldin to‘g‘ri javobni tekshiring.',speechUnavailable:'Bu brauzerda ovozli ijro mavjud emas.',scene:'Suhbatni o‘qing va vaziyatni tasavvur qiling. Har jumla ostida o‘zbekcha ma’no bor.',words:'Rasm belgilar va o‘zbekcha ma’nolar yordamida koreyscha so‘zlarni o‘rganing.',grammar:'Bu shakl qachon ishlatilishini ko‘ring va misolni ovoz chiqarib o‘qing.',listening:'Avval savolni o‘qing, so‘ng koreyscha nutqni tinglang. Matnni ham ochishingiz mumkin.',speaking:'Bugun o‘rgangan iboralar bilan o‘zingiz haqingizda ovoz chiqarib gapiring.',reading:'Asosiy fikrni o‘qib tushuning va savolga javob bering.',writing:'Koreys tilida bir necha jumla yozing. Qoralama shu brauzerda saqlanadi.',quiz:'Savollarga javob bering va davom etishdan oldin tekshiring.',tts:'Bu darslik yozuvi emas, brauzerning koreyscha sun’iy ovozi.'},
  mn:{answerFirst:'Үргэлжлүүлэхээс өмнө зөв хариултыг шалгана уу.',speechUnavailable:'Энэ хөтөч дуу тоглуулах боломжгүй.',scene:'Харилцан яриаг уншиж, нөхцөл байдлыг төсөөлөөрэй. Өгүүлбэр бүрийн доор монгол утга бий.',words:'Зурагт тэмдэг болон монгол утгаар солонгос үгийг сурна уу.',grammar:'Энэ хэлбэрийг хэзээ хэрэглэхийг үзээд жишээг чангаар уншаарай.',listening:'Эхлээд асуултыг уншаад солонгос хэлээр сонсоорой. Бичвэрийг нээж болно.',speaking:'Өнөөдөр сурсан хэллэгээр өөрийн тухай чангаар ярина уу.',reading:'Гол санааг уншаад асуултад хариулна уу.',writing:'Солонгос хэлээр хэдэн өгүүлбэр бичээрэй. Нооргийг энэ хөтөчид хадгалж болно.',quiz:'Асуултад хариулаад үргэлжлүүлэхээс өмнө шалгана уу.',tts:'Энэ нь сурах бичгийн бичлэг биш, хөтчийн солонгос хиймэл дуу хоолой юм.'}
};
const cultureGuides={ko:'짧은 문화 글을 읽고 핵심 내용을 확인해 보세요. 모르는 단어는 문맥으로 짐작해도 좋아요.',en:'Read the short culture text, then answer one question about its main idea.',ja:'短い文化の文章を読み、中心内容についての質問に答えましょう。',zh:'阅读简短的文化文章，然后回答一道有关主要内容的问题。',vi:'Đọc đoạn văn ngắn về văn hóa, rồi trả lời một câu hỏi về ý chính.',ne:'संस्कृतिबारे छोटो पाठ पढ्नुहोस् र मुख्य विचारको एउटा प्रश्नको उत्तर दिनुहोस्।',th:'อ่านบทความวัฒนธรรมสั้น ๆ แล้วตอบคำถามหนึ่งข้อเกี่ยวกับใจความสำคัญ',uz:'Madaniyat haqidagi qisqa matnni o‘qing va asosiy fikrga oid bitta savolga javob bering.',mn:'Соёлын тухай богино эхийг уншаад гол санааны нэг асуултад хариулна уу.'};
const practiceGuides={ko:'대화 내용을 묻는 문제를 풀고, 낱말을 알맞은 순서로 눌러 문장을 완성해 보세요.',en:'Answer a question about the dialogue, then tap the words in order to build its sentence.',ja:'会話の内容について答え、単語を順番に押して文を完成させましょう。',zh:'回答对话理解题，再按正确顺序点击词语组成句子。',vi:'Trả lời câu hỏi về hội thoại, rồi chạm các từ theo đúng thứ tự để tạo câu.',ne:'संवादको प्रश्नको उत्तर दिनुहोस्, अनि शब्दहरू सही क्रममा थिचेर वाक्य बनाउनुहोस्।',th:'ตอบคำถามเกี่ยวกับบทสนทนา แล้วแตะคำตามลำดับที่ถูกต้องเพื่อสร้างประโยค',uz:'Suhbat savoliga javob bering, so‘ng so‘zlarni tartib bilan bosib gap tuzing.',mn:'Харилцан ярианы асуултад хариулаад үгсийг зөв дарааллаар дарж өгүүлбэр бүтээнэ үү.'};
const puzzleGuides={ko:'문장 배열도 정확히 완성한 뒤 다음으로 가세요.',en:'Complete the sentence builder correctly before continuing.',ja:'文の並び替えも正しく完成させてから進みましょう。',zh:'请先正确完成句子排序，再继续。',vi:'Hãy sắp xếp câu đúng trước khi tiếp tục.',ne:'अगाडि बढ्नुअघि वाक्य सही क्रममा मिलाउनुहोस्।',th:'เรียงประโยคให้ถูกต้องก่อนดำเนินการต่อ',uz:'Davom etishdan oldin gapni to‘g‘ri tartibda tuzing.',mn:'Үргэлжлүүлэхээс өмнө өгүүлбэрийг зөв дарааллаар бүтээнэ үү.'};
const pageGuides={
  home:{ko:'아래 버튼을 누르면 첫 수업이 시작돼요. 왼쪽 메뉴에서 전체 단원과 복습을 볼 수 있어요.',en:'Use the button below to start. The menu on the left opens all lessons and your review.',ja:'下のボタンから始めましょう。左のメニューで全レッスンと復習を開けます。',zh:'点击下方按钮开始。左侧菜单可查看全部单元和复习。',vi:'Nhấn nút bên dưới để bắt đầu. Menu bên trái mở tất cả bài học và phần ôn tập.',ne:'सुरु गर्न तलको बटन थिच्नुहोस्। बायाँ मेनुमा सबै पाठ र पुनरावृत्ति छन्।',th:'กดปุ่มด้านล่างเพื่อเริ่ม เมนูด้านซ้ายมีบทเรียนทั้งหมดและการทบทวน',uz:'Boshlash uchun pastdagi tugmani bosing. Chap menyuda barcha darslar va takrorlash bor.',mn:'Эхлэхийн тулд доорх товчийг дарна уу. Зүүн цэсэнд бүх хичээл ба давтлага байна.'},
  units:{ko:'단원은 순서대로 열려요. 잠긴 단원은 보상 없이 둘러볼 수 있어요.',en:'Lessons unlock in order. You can preview locked lessons without rewards.',ja:'レッスンは順番に開きます。未解放のレッスンも報酬なしで見学できます。',zh:'单元按顺序解锁。未解锁的单元可以无奖励预览。',vi:'Các bài mở theo thứ tự. Bạn có thể xem trước bài bị khóa nhưng không nhận thưởng.',ne:'पाठहरू क्रमैसँग खुल्छन्। बन्द पाठ पुरस्कार बिना हेर्न सकिन्छ।',th:'บทเรียนจะปลดล็อกตามลำดับ สามารถดูบทที่ล็อกได้โดยไม่มีรางวัล',uz:'Darslar tartib bilan ochiladi. Yopiq darslarni mukofotsiz ko‘rish mumkin.',mn:'Хичээлүүд дарааллаар нээгдэнэ. Түгжээтэй хичээлийг шагналгүйгээр үзэж болно.'},
  review:{ko:'오늘 복습할 단어의 뜻을 떠올리고 기억 정도를 선택해 보세요.',en:'Recall the meaning of each word due today, then choose how well you remembered it.',ja:'今日の単語の意味を思い出し、覚えていたかを選びましょう。',zh:'回想今天待复习词汇的意思，然后选择记忆情况。',vi:'Nhớ lại nghĩa của từ cần ôn hôm nay rồi chọn mức độ bạn nhớ được.',ne:'आज दोहोर्‍याउनुपर्ने शब्दको अर्थ सम्झनुहोस् र कति सम्झनुभयो छान्नुहोस्।',th:'นึกความหมายของคำที่ต้องทบทวนวันนี้ แล้วเลือกว่าจำได้แค่ไหน',uz:'Bugun takrorlanadigan so‘z ma’nosini eslang va qanchalik eslaganingizni tanlang.',mn:'Өнөөдөр давтах үгийн утгыг санаад хэр сайн тогтоосноо сонгоно уу.'}
};
export function t(lang,key){if(key==='culture')return cultureGuides[lang]||cultureGuides.en;if(key==='practice')return practiceGuides[lang]||practiceGuides.en;if(key==='puzzleFirst')return puzzleGuides[lang]||puzzleGuides.en;if(pageGuides[key])return pageGuides[key][lang]||pageGuides[key].en;return (messages[lang]||messages.en)[key]||messages.en[key]||key;}

const grammar={
  '-고':['Connects two actions or states.','二つの動作や状態をつなぎます。','连接两个动作或状态。','Nối hai hành động hoặc trạng thái.'],
  '그런데':['Introduces a different or contrasting situation.','前の内容と異なる状況を続けます。','引出与前文不同的情况。','Chuyển sang tình huống khác hoặc tương phản.'],
  '못':['Place before a verb to say you cannot do something.','動詞の前に置き、できないことを表します。','放在动词前表示不能做某事。','Đặt trước động từ để nói không thể làm việc gì.'],
  '-아서/어서':['Gives a reason or links actions in order.','理由や動作の順序を表します。','表示原因或动作的先后。','Nêu lý do hoặc nối các hành động theo thứ tự.'],
  '-(으)ㄹ래요':['Asks or says what someone wants to do.','したいことを尋ねたり伝えたりします。','询问或表达想做的事。','Hỏi hoặc nói điều muốn làm.'],
  '무슨':['Asks what kind of thing it is.','どんな種類かを尋ねます。','询问是哪一种。','Hỏi đó là loại gì.'],
  '이/가 걸리다':['States how much time something takes.','必要な時間を表します。','表示需要花费的时间。','Nói một việc mất bao lâu.'],
  '-에서 -까지':['Marks the starting point and destination.','出発地と目的地を示します。','标记出发地和目的地。','Chỉ điểm xuất phát và điểm đến.'],
  '(으)로':['Shows a direction or route.','移動する方向や経路を表します。','表示方向或路线。','Chỉ hướng hoặc đường đi.'],
  '-아/어 주다':['Asks someone to do something for another person.','人のためにする動作や依頼を表します。','表示为别人做某事或提出请求。','Nhờ ai làm việc gì cho người khác.'],
  '-지요?':['Checks whether the listener agrees or knows.','相手に確認や同意を求めます。','向对方确认或征求同意。','Hỏi xác nhận hoặc tìm sự đồng ý.'],
  '-(으)ㄴ':['Turns an adjective into a description before a noun.','形容詞で後ろの名詞を修飾します。','让形容词修饰后面的名词。','Dùng tính từ để bổ nghĩa cho danh từ phía sau.'],
  '-고 있다':['Describes an ongoing action or what someone is wearing.','進行中の動作や身につけている状態を表します。','描述正在进行的动作或穿戴状态。','Diễn tả hành động đang diễn ra hoặc trang phục đang mặc.'],
  '의':['Shows possession or a relationship between nouns.','所有や名詞同士の関係を表します。','表示所属或名词之间的关系。','Chỉ sở hữu hoặc mối quan hệ giữa các danh từ.'],
  '-(으)시-':['Shows respect toward the person doing the action.','動作をする人への敬意を表します。','对动作的主体表示尊敬。','Thể hiện sự kính trọng với người thực hiện hành động.'],
  '-아/어 보다':['Says you have tried or experienced something.','試した経験を表します。','表示尝试过或有过某种经历。','Nói rằng đã thử hoặc trải nghiệm một việc.'],
  '-고 싶다':['Says what you want to do.','したいことを表します。','表达想做的事。','Nói điều mình muốn làm.'],
  '-지 말다':['Tells someone not to do an action.','しないように伝えます。','表示劝告别人不要做某事。','Khuyên ai đó đừng làm một việc.'],
  '-(으)ㄴ 후에':['Means after an action is finished.','動作が終わった後を表します。','表示某动作完成之后。','Chỉ thời điểm sau khi hành động kết thúc.'],
  '-아야/어야 하다':['Says something must be done.','しなければならないことを表します。','表示必须做某事。','Nói việc bắt buộc phải làm.'],
  '-(으)ㄹ게요':['Promises or offers to do something for the listener.','相手に約束や意志を伝えます。','向对方表示承诺或意愿。','Hứa hoặc đề nghị sẽ làm việc gì.'],
  '-지만':['Connects two contrasting ideas.','対照的な二つの内容をつなぎます。','连接两个相反的意思。','Nối hai ý tương phản.'],
  '보다':['Marks the thing used for comparison.','比較の基準を示します。','标记比较的对象。','Đánh dấu đối tượng được đem ra so sánh.'],
  '-(으)ㄹ 때':['Means when something happens.','あることが起こる時を表します。','表示某事发生的时候。','Có nghĩa là khi một việc xảy ra.'],
  '-(으)러 가다':['Says the purpose of going somewhere.','行く目的を表します。','表示去某地的目的。','Nói mục đích đi đến đâu đó.'],
  '-(으)려고':['Explains the purpose or intention of an action.','行動の目的や意図を表します。','说明行动的目的或意图。','Giải thích mục đích hoặc ý định của hành động.'],
  '-(으)면':['Introduces an if-condition.','「もし～なら」という条件を表します。','表示“如果……”的条件。','Nêu điều kiện “nếu…”.']
};
export function grammarHelp(lang,pattern){if(lang==='ko')return '';const key=pattern==='-아/어서'?'-아서/어서':pattern;if(extraGrammar[lang]?.[key])return extraGrammar[lang][key];const row=grammar[key];if(!row)return '';return row[{en:0,ja:1,zh:2,vi:3}[lang]??0];}
